// AUTH
export const SET_USER = 'SET_USER'

// BUDGETS
export const ADD_BUDGET = 'ADD_BUDGET'
export const DELETE_BUDGET = 'DELETE_BUDGET'
export const SET_BUDGET = 'SET_BUDGET'
export const SET_BUDGETS = 'SET_BUDGETS'
export const SET_DATE_ONE = 'SET_DATE_ONE'
export const SET_DATE_TWO = 'SET_DATE_TWO'

// ITEMS
export const ADD_ITEM = 'ADD_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const SET_ITEMS = 'SET_ITEMS'
export const SET_ITEM = 'SET_ITEM'

// TRANSACTIONS
export const ADD_TRANSACTION = 'ADD_TRANSACTION'
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION'
export const SET_TRANSACTIONS = 'SET_TRANSACTIONS'
export const SET_TRANSACTION = 'SET_TRANSACTION'
