version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.4
  aws-s3: circleci/aws-s3@1.0.4
references:
  - &set_up_environment_variables
    run:
      name: Setup common environment variables
      command: |
        echo 'REACT_APP_PLAID_ENV=${PLAID_ENV}' >> $BASH_ENV
        echo 'REACT_APP_PLAID_PUBLIC_KEY=${PLAID_PUBLIC_KEY}' >> $BASH_ENV
  - &aws_configure
    aws-cli/configure:
      aws-access-key-id: $AWS_ACCESS_KEY_ID
      aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
      aws-region: "$AWS_DEFAULT_REGION"
  - &s3_sync
    run:
      name: Deploy to S3
      command: |
        aws s3 sync workspace/build s3://${AWS_S3_BUCKET_NAME} --delete
jobs:
  build:
    docker:
      - image: circleci/node:9.10
    steps:
      - checkout
      - setup_remote_docker
      - *set_up_environment_variables
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: |
            yarn --prod --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build app for production
          command: |
            yarn build
      - persist_to_workspace:
          root: .
          paths:
            - build
  deploy:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: workspace
      - aws-cli/install
      - *aws_configure
      - *set_up_environment_variables
      - *s3_sync
workflows:
  build-deploy:
    jobs:
      - build:
          context: butter
      - deploy:
          context: butter
          requires:
            - build
          filters:
            branches:
              only: master
